"""Shared utilities: logging, exceptions, retries, filesystem, media math and preflight.

Import order matters here. ``config.settings`` imports ``utils.exceptions``, so nothing this
package imports at module scope may import ``config.settings`` in turn. Every module below
takes the settings it needs as an argument instead, and ``utils.preflight`` refers to the
``Settings`` type only under ``TYPE_CHECKING``.
"""

from utils.exceptions import (
    ConfigurationError,
    DiskSpaceError,
    FontNotFoundError,
    MediaDownloadError,
    MediaNotFoundError,
    MediaProviderError,
    PipelineError,
    PreflightError,
    RenderError,
    ScenarioValidationError,
    SubtitleError,
    TTSError,
    UploadAuthError,
    UploadError,
    UploadQuotaError,
)
from utils.fs import (
    atomic_write_bytes,
    atomic_write_text,
    available_fonts,
    clear_directory,
    default_fonts_dir,
    download_default_font,
    ensure_parent,
    file_sha256,
    font_is_resolvable,
    format_bytes,
    free_disk_bytes,
    hash_payload,
    human_duration,
    read_json,
    require_free_disk,
    resolve_font,
    safe_filename,
    temporary_path,
    write_json,
)
from utils.logger import (
    SecretRedactingFilter,
    console,
    get_logger,
    log_error,
    log_info,
    log_metric,
    log_step,
    log_success,
    log_warn,
    make_download_progress,
    make_step_progress,
    redact,
    register_secret,
    setup_logging,
    summary_table,
    table_box,
)
from utils.media import (
    CropPlan,
    aspect_ratio,
    classify_orientation,
    distribute_duration,
    ffmpeg_executable,
    make_even,
    matches_orientation,
    plan_scale_and_crop,
    probe_duration,
    resolution_for_orientation,
    zoom_scale_at,
)
from utils.preflight import CheckResult, raise_if_failed, run_all_checks
from utils.retry import is_retryable_exception, make_retrying, retry_http_call, status_is_retryable

__all__ = [
    "CheckResult",
    "ConfigurationError",
    "CropPlan",
    "DiskSpaceError",
    "FontNotFoundError",
    "MediaDownloadError",
    "MediaNotFoundError",
    "MediaProviderError",
    "PipelineError",
    "PreflightError",
    "RenderError",
    "ScenarioValidationError",
    "SecretRedactingFilter",
    "SubtitleError",
    "TTSError",
    "UploadAuthError",
    "UploadError",
    "UploadQuotaError",
    "aspect_ratio",
    "atomic_write_bytes",
    "atomic_write_text",
    "available_fonts",
    "classify_orientation",
    "clear_directory",
    "console",
    "default_fonts_dir",
    "distribute_duration",
    "download_default_font",
    "ensure_parent",
    "ffmpeg_executable",
    "file_sha256",
    "font_is_resolvable",
    "format_bytes",
    "free_disk_bytes",
    "get_logger",
    "hash_payload",
    "human_duration",
    "is_retryable_exception",
    "log_error",
    "log_info",
    "log_metric",
    "log_step",
    "log_success",
    "log_warn",
    "make_download_progress",
    "make_even",
    "make_retrying",
    "make_step_progress",
    "matches_orientation",
    "plan_scale_and_crop",
    "probe_duration",
    "raise_if_failed",
    "read_json",
    "redact",
    "register_secret",
    "require_free_disk",
    "resolution_for_orientation",
    "resolve_font",
    "retry_http_call",
    "run_all_checks",
    "safe_filename",
    "setup_logging",
    "status_is_retryable",
    "summary_table",
    "table_box",
    "temporary_path",
    "write_json",
    "zoom_scale_at",
]
